### ISSUE TITLE
Crash report #01

### ISSUE THREAD

**Issue by squarecattest** [squarecattest/Pygame_Sudoku#1]
Game crashes when trying to solve a puzzle which is fully filled by bot.

Traceback (most recent call last):
  File ".\Sudoku\latest\main.py", line 78, in <module>
    screen_state = puzzle_page.action(control)
    self.solve_by_bot()
  File ".\Sudoku\latest\puzzle.py", line 441, in solve_by_bot      
    self.puzzle.solve()
  File ".\Sudoku\latest\puzzle.py", line 174, in solve
    solution = sudoku.Sudoku(self.__puzzle)
  File ".\Sudoku\latest\sudoku.py", line 21, in \_\_init\_\_
    self.guess_indexs = self.next_guess_index(*guess_indexs)
  File ".\Sudoku\latest\sudoku.py", line 40, in next_guess_index   
    while self.puzzle[i][j]:
IndexError: list index out of range

**Comment by squarecattest** [comment]
Solved by adding line in sudoku.Sudoku.next_guess_index (line 42):
if i == 9: raise Unsolvable
